app:
  port: 80
  image: davidcrty/crty-dev
  ingress:
    type: IngressRoute
    enabled: true
    hosts:
      - crty.dev
      - www.crty.dev
    redirections:
      - from:
          - www.crty.dev
        to: crty.dev